### ISSUE TITLE
Handling empty tables as objects or lists

### ISSUE THREAD

**Issue by seancribbs** [bjornbytes/graphql-lua#14]
@bjornbytes Thank you for merging my previous PRs. Before I send my next one, I wanted to discuss it with you (copying my comment into this issue from gitter).

The essential problem is that whatever JSON serialization library you use has to be able to distinguish between empty Lists and Objects as intended by GraphQL. Because Lua uses the same type, tables, for this purpose, it is non-obvious which one to emit. In our internal fork, we have patched `graphql-lua` to require `resty.libcjson`, which lets you set the metatable to indicate which type it should be in the output. If this is an acceptable dependency for you, I'll send the PR right away. Otherwise, I'd love to hear your thoughts on the matter.

**Comment by bjornbytes** [comment]
If possible, I'd like to avoid coupling this project to any particular JSON library.  Does this do what you want?

https://github.com/bjornbytes/graphql-lua/compare/json-tables

If you do `local schema = require 'graphql.schema'`, then you can override `schema.__emptyObject` or `schema.__emptyList` to change the value returned when an object or list is empty, respectively.  You can also change the value for a specific schema by passing in those keys when creating the schema.

To integrate with `resty.libcjson`, you could do `schema.__emptyObject = setmetatable({}, json.object)`.

Another option might be to add a sixth argument to `execute` for the sentinel values.  What did you come up with?

**Comment by seancribbs** [comment]
That's an interesting approach, I'll try that patch locally against our regression tests and let you know.
